### PR TITLE
tests: wait for all pindexes of search index ready before analyzing the document

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Review by brett19 — APPROVED** [review]

**Review by brett19 — APPROVED** [review]

**Comment by avsej** [comment]
Jenkins, test this, please.

**Comment by avsej** [comment]
Jenkins, test this, please.

**Comment by avsej** [comment]
Jenkins, test this, please.

**Comment by avsej** [comment]
Jenkins, test this, please.

**Pull request merged**
