### PR TITLE
CXXCBC-332: hide implementation of the core::cluster class

### PR DESCRIPTION
**Pull request by avsej**
<table>
  <tr>
    <th></th>
    <th>Before</th>
    <th>After</th>
    <th>Diff</th>
  </tr>
  <tr>
    <td>MacOS</td>
    <td>7m22s</td>
    <td>5m9s</td>
    <td>-2m13s (-26%)</td>
  </tr>
  <tr>
    <td>Linux</td>
    <td>17m13s</td>
    <td>14m31s</td>
    <td>-2m42s (-15%)</td>
  </tr>
  <tr>
    <td>Windows</td>
    <td>18m20s</td>
    <td>13m10s</td>
    <td>-5m10s (-28%)</td>
  </tr>
</table>

## MacOS

2.6 GHz 6-Core Intel Core i7

```
$ ccache -C
$ cmake -DENABLE_CACHE=OFF ..
$ time ninja -j8
```

Before:
```
real    7m22.705s
user    54m18.030s
sys 3m4.835s
```

After:
```
real    5m9.616s
user    35m4.388s
sys 2m29.979s
```

## Linux

Intel® Core™ i7-6820HQ 4 cores, 8 threads

```
cmake -DENABLE_CACHE=OFF -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
```

### Before
```
real    17m13.565s
user    95m0.353s
sys 7m23.323s
```

### After

```
real    14m31.595s
user    61m16.772s
sys 5m55.496s
```
## Windows

Intel Pentium Gold 7505 @ 2.00GHz, 1997 Mhz, 2 Core(s), 4 Logical Processor(s)

```
cmake -DENABLE_CACHE=OFF ..
```

### Before
```
$result = Measure-Command -Expression { cmake --build . --parallel 4 }; $result.ToString()
00:18:20.9621881
```

### After

```
$result = Measure-Command -Expression { cmake --build . --parallel 4 }; $result.ToString()
00:13:10.5661511
```

### CODE REVIEW

**Comment by avsej** [comment]
The jenkins is red right now because scripts fail to initialize FTS index. This is going to be fixed in https://github.com/couchbaselabs/couchbase-cxx-client/pull/414.

**Comment by avsej** [comment]
image
image

**Comment by avsej** [comment]
image
image

**Review by thejcfactor — APPROVED** [review]
Have been able to complete builds w/ Python and Node.js wrappers.  Tests appear to be okay as well.  Build times on linux for the Node.js client have reduced by ~20 min which is nice 😄.

**Pull request merged**
