### PR TITLE
OpenSSL and CentOS 7

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by avsej** [comment]
jenkins, test this please

**Comment by avsej** [comment]
jenkins, test this please

**Comment by avsej** [comment]
Jenkins, test this please

**Comment by avsej** [comment]
jenkins, test this please

**Comment by avsej** [comment]
jenkins, test this please

**Review by thejcfactor — APPROVED** [review]
Well done!! Will be nice to avoid some headaches we have had in the past with certain OSes and OpenSSL. 👍

**Pull request merged**
